### PR TITLE
Add JSON formatter

### PR DESCRIPTION
**Pull request by mootpointer**
This adds a `:formatter` option to the plug, which lets you chose which
formatter you wish to use.

Formatting for the current format has been moved to `Logster.StringFormatter`
and a new `Logster.JSONFormatter` has been added to provide the JSON
formatting.

Still to do:
- [x]  Update Documentation
- [ ]  ???

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/navinpeiris/logster/pull/4" target="_blank">ReviewNinja

**Comment by navinpeiris** [comment]
So sorry @mootpointer, been crazy busy the last couple of days. Looks good to me! If you can add something to the README as well, I'll merge and push a new version through

**Comment by mootpointer** [comment]
@navinpeiris Done.

**Comment by navinpeiris** [comment]
Wow, beautiful! Thanks @mootpointer!

**Comment by mootpointer** [comment]
Closes #3

**Comment by navinpeiris** [comment]
version `0.2.0` released with your changes @mootpointer

**Pull request merged**
