### PR TITLE
Add metadata to log

### PR DESCRIPTION
**Pull request by tanguyantoine**
- allow users to add additionnal data to their log

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/navinpeiris/logster/pull/6" target="_blank">ReviewNinja

**Comment by tanguyantoine** [comment]
Sorry i forgot tests. Working on that

**Comment by tanguyantoine** [comment]
Done :)

**Comment by tanguyantoine** [comment]
🆙

**Comment by ypaq** [comment]
+1

**Comment by numidiasoft** [comment]
👍 +1

**Comment by gmontard** [comment]
👍 +1

**Comment by freiden** [comment]
👍

**Comment by yasseur1007** [comment]
👍

**Comment by navinpeiris** [comment]
Thanks @tanguyantoine, and sorry for the delay in getting it out. I've published version `0.3.0` with your changes.

**Pull request merged**
